In [1]:
import numpy as np

# define the 3x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# calculate the mean of the columns
mean_cols = np.mean(A, axis=0)

# subtract the mean from the original matrix to get the centered matrix
centered_matrix = A - mean_cols

# calculate the covariance matrix of the centered matrix
cov_matrix = np.cov(centered_matrix, rowvar=False)

# calculate the eigenvectors and eigenvalues of the covariance matrix
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# sort the eigenvectors in descending order of eigenvalues
idx = eigenvalues.argsort()[::-1]
eigenvectors = eigenvectors[:,idx]

# transform the centered matrix using the eigenvectors to get the PCA scores
pca_scores = np.dot(centered_matrix, eigenvectors)

# print the PCA scores
print(pca_scores)


[[-5.19615242e+00  4.44089210e-16  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.19615242e+00 -4.44089210e-16 -1.11022302e-16]]
